"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { TourInput } from "@/lib/thrive-engine"
import { Loader2, Save, Plus, Trash2 } from "lucide-react"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

interface CustomFieldDefinition {
    id: number;
    label: string;
    key: string;
    type: string;
    options: string | null;
}

interface TourEditModalProps {
    tour?: TourInput | null
    isOpen: boolean
    onClose: () => void
    onSave: () => void
}

export function TourEditModal({ tour, isOpen, onClose, onSave }: TourEditModalProps) {
    const [isLoading, setIsLoading] = useState(false)
    const [customFieldDefs, setCustomFieldDefs] = useState<CustomFieldDefinition[]>([])
    const [formData, setFormData] = useState<Partial<TourInput>>({
        id: "",
        name: "",
        provider: "",
        netRate: 0,
        publicPrice: 0,
        duration: "",
        opsDays: "",
        cxlPolicy: "",
        meetingPoint: "",
        landingPageUrl: "",
        storytelling: "",
        location: "",
        region: "",
        activityType: "",
        tourType: "",
        images: [],
        variants: [],
        custom_fields: []
    })

    // Fetch custom field definitions on mount
    useEffect(() => {
        const fetchDefinitions = async () => {
            try {
                const response = await fetch('/api/custom-fields');
                const data = await response.json();
                if (data.success) {
                    setCustomFieldDefs(data.data);
                }
            } catch (error) {
                console.error('Failed to fetch custom field definitions:', error);
            }
        };

        if (isOpen) {
            fetchDefinitions();
        }
    }, [isOpen]);

    // Populate form when editing existing tour
    useEffect(() => {
        if (tour) {
            setFormData({
                ...tour,
                variants: tour.variants || [],
                custom_fields: tour.custom_fields || []
            })
        } else {
            // Reset for new tour
            setFormData({
                id: "",
                name: "",
                provider: "",
                netRate: 0,
                publicPrice: 0,
                duration: "",
                opsDays: "",
                cxlPolicy: "",
                meetingPoint: "",
                landingPageUrl: "",
                storytelling: "",
                location: "",
                region: "",
                activityType: "",
                tourType: "",
                images: [],
                variants: [],
                custom_fields: []
            })
        }
    }, [tour, isOpen])

    const handleSave = async () => {
        setIsLoading(true)
        try {
            const method = tour ? 'PUT' : 'POST'
            const url = tour ? `/api/tours/${tour.id}` : '/api/tours'

            // Prepare nested payload for API
            const sharedFactor = formData.netRate && formData.publicPrice
                ? parseFloat((formData.publicPrice / formData.netRate).toFixed(2))
                : 1.5;

            const payload = {
                // Core
                id: formData.id, // Only for new manual ID if allowed, usually autogenerated or ignored on update
                product_name: formData.name,
                supplier: formData.provider,
                location: formData.location,
                is_active: true, // Default to true for now

                // Nested Relations
                pricing: {
                    net_rate_adult: Number(formData.netRate),
                    shared_factor: sharedFactor,
                    // We don't have inputs for child/private yet in this modal main view, 
                    // but we should preserve them if they were in the original tour? 
                    // detailed preservation would require storing them in formData. 
                    // For now, let's assume we update what we see.
                    // If we want to support full editing, we need to map all fields.
                    // Let's stick to the visible fields for now.
                    net_rate_child: formData.netChild,
                    net_rate_private: formData.netPrivate,
                    private_factor: formData.factorPrivate,
                    shared_min_pax: formData.minPaxShared,
                    private_min_pax: formData.minPaxPrivate,
                    infant_age_threshold: formData.infantAge,
                    extra_fees: formData.extraFees
                },
                logistics: {
                    duration: formData.duration,
                    days_of_operation: formData.opsDays,
                    cxl_policy: formData.cxlPolicy,
                    meeting_point_info: formData.meetingPoint,
                    pickup_info: formData.meetingPoint // Map to both if unclear
                },
                assets: {
                    landing_page_url: formData.landingPageUrl,
                    storytelling_url: formData.storytelling,
                    notes: formData.auditNotes,
                    pictures_url: formData.images && formData.images.length > 0 ? formData.images[0] : undefined
                },

                // Arrays
                variants: formData.variants?.map(v => ({
                    ...v,
                    // If creating new, id might be missing, handled by API
                    net_rate_adult: Number(v.net_rate_adult),
                    net_rate_child: v.net_rate_child ? Number(v.net_rate_child) : null
                })),
                custom_fields: formData.custom_fields?.map(f => ({
                    definition_id: Number(f.definition_id),
                    value: String(f.value)
                }))
            };

            const response = await fetch(url, {
                method,
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            })

            if (!response.ok) {
                const error = await response.text()
                throw new Error(error)
            }

            onSave()
            onClose()
        } catch (error) {
            console.error('Save error:', error)
            alert(`Error al guardar: ${error}`)
        } finally {
            setIsLoading(false)
        }
    }

    const addVariant = () => {
        setFormData({
            ...formData,
            variants: [
                ...(formData.variants || []),
                {
                    name: "New Variant",
                    net_rate_adult: 0,
                    is_active: true
                }
            ]
        })
    }

    const updateVariant = (index: number, field: string, value: any) => {
        const newVariants = [...(formData.variants || [])];
        newVariants[index] = { ...newVariants[index], [field]: value };
        setFormData({ ...formData, variants: newVariants });
    }

    const removeVariant = (index: number) => {
        const newVariants = [...(formData.variants || [])];
        newVariants.splice(index, 1);
        setFormData({ ...formData, variants: newVariants });
    }

    const updateCustomField = (defId: number, value: string) => {
        const currentFields = [...(formData.custom_fields || [])];
        const existingIndex = currentFields.findIndex(f => f.definition_id === defId);

        if (existingIndex >= 0) {
            currentFields[existingIndex] = { ...currentFields[existingIndex], value };
        } else {
            currentFields.push({ definition_id: defId, value });
        }

        setFormData({ ...formData, custom_fields: currentFields });
    }

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="sm:max-w-[900px] bg-gray-900 border-gray-800 text-white max-h-[90vh] overflow-y-auto">
                <DialogHeader>
                    <DialogTitle>{tour ? `Editar Tour: ${tour.name}` : 'Nuevo Tour'}</DialogTitle>
                    <DialogDescription className="text-gray-400">
                        {tour ? 'Actualiza la información del tour' : 'Crea un nuevo tour en el inventario'}
                    </DialogDescription>
                </DialogHeader>

                <Tabs defaultValue="general" className="w-full">
                    <TabsList className="grid w-full grid-cols-3 bg-gray-800 text-gray-400">
                        <TabsTrigger value="general">General Info</TabsTrigger>
                        <TabsTrigger value="variants">Variants ({formData.variants?.length || 0})</TabsTrigger>
                        <TabsTrigger value="custom-fields">Custom Fields</TabsTrigger>
                    </TabsList>

                    <div className="py-4">
                        <TabsContent value="general" className="grid gap-6">
                            {/* Basic Info */}
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <Label htmlFor="id" className="text-gray-300">ID *</Label>
                                    <Input
                                        id="id"
                                        value={formData.id}
                                        onChange={(e) => setFormData({ ...formData, id: e.target.value })}
                                        className="bg-gray-950 border-gray-800 text-gray-300"
                                        disabled={!!tour}
                                        placeholder="ID único del tour"
                                    />
                                </div>
                                <div>
                                    <Label htmlFor="provider" className="text-gray-300">Proveedor *</Label>
                                    <Input
                                        id="provider"
                                        value={formData.provider}
                                        onChange={(e) => setFormData({ ...formData, provider: e.target.value })}
                                        className="bg-gray-950 border-gray-800 text-gray-300"
                                        placeholder="Ej: Mundo Maya"
                                    />
                                </div>
                            </div>

                            <div>
                                <Label htmlFor="name" className="text-gray-300">Nombre del Tour *</Label>
                                <Input
                                    id="name"
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                    className="bg-gray-950 border-gray-800 text-gray-300"
                                    placeholder="Ej: Holbox Dream Tour"
                                />
                            </div>

                            {/* Economics */}
                            <div className="border-t border-gray-800 pt-4">
                                <h3 className="font-semibold text-teal-400 mb-3">💰 Economics</h3>
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <Label htmlFor="netRate" className="text-gray-300">Net Rate (USD) *</Label>
                                        <Input
                                            id="netRate"
                                            type="number"
                                            value={formData.netRate ?? 0}
                                            onChange={(e) => setFormData({ ...formData, netRate: parseFloat(e.target.value) || 0 })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="0.00"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="publicPrice" className="text-gray-300">Public Price (USD)</Label>
                                        <Input
                                            id="publicPrice"
                                            type="number"
                                            value={formData.publicPrice ?? 0}
                                            onChange={(e) => setFormData({ ...formData, publicPrice: parseFloat(e.target.value) || 0 })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="0.00"
                                        />
                                    </div>
                                </div>
                            </div>

                            {/* Categorization */}
                            <div className="border-t border-gray-800 pt-4">
                                <h3 className="font-semibold text-blue-400 mb-3">📍 Categorization</h3>
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <Label htmlFor="location" className="text-gray-300">Location (State)</Label>
                                        <Input
                                            id="location"
                                            value={formData.location ?? ""}
                                            onChange={(e) => setFormData({ ...formData, location: e.target.value })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="Ej: Quintana Roo"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="region" className="text-gray-300">Region</Label>
                                        <Input
                                            id="region"
                                            value={formData.region ?? ""}
                                            onChange={(e) => setFormData({ ...formData, region: e.target.value })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="Ej: Riviera Maya"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="activityType" className="text-gray-300">Activity Type</Label>
                                        <Input
                                            id="activityType"
                                            value={formData.activityType ?? ""}
                                            onChange={(e) => setFormData({ ...formData, activityType: e.target.value })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="Ej: Acuática, Cultural, Extrema"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="tourType" className="text-gray-300">Tour Type</Label>
                                        <Input
                                            id="tourType"
                                            value={formData.tourType ?? ""}
                                            onChange={(e) => setFormData({ ...formData, tourType: e.target.value })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="Ej: Compartido, Privado"
                                        />
                                    </div>
                                </div>
                            </div>

                            {/* Technical Specs */}
                            <div className="border-t border-gray-800 pt-4">
                                <h3 className="font-semibold text-purple-400 mb-3">📋 Technical Specs</h3>
                                <div className="grid grid-cols-3 gap-4">
                                    <div>
                                        <Label htmlFor="duration" className="text-gray-300">Duration</Label>
                                        <Input
                                            id="duration"
                                            value={formData.duration ?? ""}
                                            onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="Ej: 12 Hours"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="opsDays" className="text-gray-300">Ops Days</Label>
                                        <Input
                                            id="opsDays"
                                            value={formData.opsDays ?? ""}
                                            onChange={(e) => setFormData({ ...formData, opsDays: e.target.value })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="Ej: Daily, Mon-Fri"
                                        />
                                    </div>
                                    <div>
                                        <Label htmlFor="cxlPolicy" className="text-gray-300">Cancellation Policy</Label>
                                        <Input
                                            id="cxlPolicy"
                                            value={formData.cxlPolicy ?? ""}
                                            onChange={(e) => setFormData({ ...formData, cxlPolicy: e.target.value })}
                                            className="bg-gray-950 border-gray-800 text-gray-300"
                                            placeholder="Ej: 24 Hours"
                                        />
                                    </div>
                                </div>
                                <div className="mt-4">
                                    <Label htmlFor="meetingPoint" className="text-gray-300">Meeting Point</Label>
                                    <Input
                                        id="meetingPoint"
                                        value={formData.meetingPoint ?? ""}
                                        onChange={(e) => setFormData({ ...formData, meetingPoint: e.target.value })}
                                        className="bg-gray-950 border-gray-800 text-gray-300"
                                        placeholder="Ej: Hotel Lobby"
                                    />
                                </div>
                            </div>

                            {/* Marketing */}
                            <div className="border-t border-gray-800 pt-4">
                                <h3 className="font-semibold text-orange-400 mb-3">🎯 Marketing</h3>
                                <div className="mb-4">
                                    <Label htmlFor="landingPageUrl" className="text-gray-300">Landing Page URL</Label>
                                    <Input
                                        id="landingPageUrl"
                                        value={formData.landingPageUrl ?? ""}
                                        onChange={(e) => setFormData({ ...formData, landingPageUrl: e.target.value })}
                                        className="bg-gray-950 border-gray-800 text-gray-300"
                                        placeholder="https://..."
                                    />
                                </div>
                                <div>
                                    <Label htmlFor="storytelling" className="text-gray-300">Storytelling</Label>
                                    <Textarea
                                        id="storytelling"
                                        value={formData.storytelling ?? ""}
                                        onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => setFormData({ ...formData, storytelling: e.target.value })}
                                        className="bg-gray-950 border-gray-800 text-gray-300 h-24"
                                        placeholder="Descripción atractiva del tour..."
                                    />
                                </div>
                            </div>
                        </TabsContent>

                        <TabsContent value="variants" className="space-y-4">
                            <div className="flex justify-between items-center mb-4">
                                <h3 className="text-lg font-medium text-gray-200">Tour Variants</h3>
                                <Button onClick={addVariant} size="sm" className="bg-teal-600 hover:bg-teal-700">
                                    <Plus className="h-4 w-4 mr-2" /> Add Variant
                                </Button>
                            </div>

                            {formData.variants?.length === 0 ? (
                                <div className="text-center py-8 border border-dashed border-gray-700 rounded-lg">
                                    <p className="text-gray-500">No variants added yet.</p>
                                </div>
                            ) : (
                                <div className="space-y-4">
                                    {formData.variants?.map((variant, index) => (
                                        <div key={index} className="bg-gray-800 p-4 rounded-lg border border-gray-700 space-y-4">
                                            <div className="flex justify-between items-start">
                                                <div className="grid grid-cols-2 gap-4 w-full mr-4">
                                                    <div>
                                                        <Label className="text-gray-400 text-xs">Name</Label>
                                                        <Input
                                                            value={variant.name}
                                                            onChange={(e) => updateVariant(index, 'name', e.target.value)}
                                                            className="bg-gray-950 border-gray-700 h-9"
                                                        />
                                                    </div>
                                                    <div>
                                                        <Label className="text-gray-400 text-xs">Duration</Label>
                                                        <Input
                                                            value={variant.duration || ''}
                                                            onChange={(e) => updateVariant(index, 'duration', e.target.value)}
                                                            className="bg-gray-950 border-gray-700 h-9"
                                                            placeholder="e.g. 4 Hours"
                                                        />
                                                    </div>
                                                    <div>
                                                        <Label className="text-gray-400 text-xs">Net Rate (Adult)</Label>
                                                        <Input
                                                            type="number"
                                                            value={variant.net_rate_adult}
                                                            onChange={(e) => updateVariant(index, 'net_rate_adult', e.target.value)}
                                                            className="bg-gray-950 border-gray-700 h-9"
                                                        />
                                                    </div>
                                                    <div>
                                                        <Label className="text-gray-400 text-xs">Net Rate (Child)</Label>
                                                        <Input
                                                            type="number"
                                                            value={variant.net_rate_child || ''}
                                                            onChange={(e) => updateVariant(index, 'net_rate_child', e.target.value)}
                                                            className="bg-gray-950 border-gray-700 h-9"
                                                            placeholder="Optional"
                                                        />
                                                    </div>
                                                    <div className="col-span-2">
                                                        <Label className="text-gray-400 text-xs">Description</Label>
                                                        <Input
                                                            value={variant.description || ''}
                                                            onChange={(e) => updateVariant(index, 'description', e.target.value)}
                                                            className="bg-gray-950 border-gray-700 h-9"
                                                            placeholder="Variant description..."
                                                        />
                                                    </div>
                                                </div>
                                                <Button
                                                    variant="ghost"
                                                    size="icon"
                                                    className="text-red-400 hover:text-red-300 hover:bg-transparent -mt-1"
                                                    onClick={() => removeVariant(index)}
                                                >
                                                    <Trash2 className="h-5 w-5" />
                                                </Button>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </TabsContent>

                        <TabsContent value="custom-fields" className="space-y-4">
                            <div className="mb-4">
                                <h3 className="text-lg font-medium text-gray-200">Custom Fields</h3>
                                <p className="text-sm text-gray-500">Values for custom defined fields.</p>
                            </div>

                            {customFieldDefs.length === 0 ? (
                                <div className="text-center py-8 bg-gray-900 rounded-lg">
                                    <p className="text-gray-500">No custom field definitions found. Go to Settings to create them.</p>
                                </div>
                            ) : (
                                <div className="grid gap-6">
                                    {customFieldDefs.map((def) => {
                                        const value = formData.custom_fields?.find(f => f.definition_id === def.id)?.value || '';
                                        return (
                                            <div key={def.id}>
                                                <Label className="text-gray-300 mb-2 block">{def.label}</Label>
                                                <Input
                                                    value={value}
                                                    onChange={(e) => updateCustomField(def.id, e.target.value)}
                                                    className="bg-gray-950 border-gray-800 text-gray-300"
                                                    placeholder={`Enter ${def.label}...`}
                                                />
                                                <p className="text-xs text-gray-500 mt-1">Type: {def.type}</p>
                                            </div>
                                        );
                                    })}
                                </div>
                            )}
                        </TabsContent>
                    </div>

                    <DialogFooter className="mt-6 border-t border-gray-800 pt-4">
                        <Button variant="outline" onClick={onClose} className="border-gray-700 text-gray-400">
                            Cancelar
                        </Button>
                        <Button onClick={handleSave} disabled={isLoading} className="bg-teal-600 hover:bg-teal-500">
                            {isLoading ? (
                                <>
                                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                    Guardando...
                                </>
                            ) : (
                                <>
                                    <Save className="mr-2 h-4 w-4" />
                                    Guardar
                                </>
                            )}
                        </Button>
                    </DialogFooter>
                </Tabs>
            </DialogContent>
        </Dialog>
    )
}
